<a href="https://colab.research.google.com/github/Hirunikathaluwage/EAD_Big_Data_Analysis/blob/main/EAS_BigData_Analytics_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df = pd.read_csv('/content/drive/MyDrive/EAD/samplesuperstore.csv')

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [4]:
df.shape

(10194, 21)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [7]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop_duplicates()

In [13]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date']  = pd.to_datetime(df['Ship Date'])

In [15]:
df['Delivery Days'] = (df['Ship Date']-df['Order Date']).dt.days

In [16]:
df.head

<bound method NDFrame.head of        Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2           3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3           4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4           5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...       ...             ...        ...        ...             ...
10189   10190  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10190   10191  US-2026-115427 2026-12-30 2027-01-03  Standard Class
10191   10192  US-2026-156720 2026-12-30 2027-01-03  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10193   10194  CA-2026-143500 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ...   Region       Product ID         Category  \
0            Houston  ...  Central  OFF-PA-10000174  Office Supplies
1         Naperville  ...  Central  OFF-BI-10004094  Office Supplies
2         Naperville  ...  Central  OFF-LA-10003223  Office Supplies
3         Naperville  ...  Central  OFF-ST-10002743  Office Supplies
4       Philadelphia  ...     East  OFF-AR-10003478  Office Supplies
...              ...  ...      ...              ...              ...
10189  New York City  ...     East  OFF-BI-10003684  Office Supplies
10190      Fairfield  ...     West  OFF-BI-10004632  Office Supplies
10191       Loveland  ...     West  OFF-FA-10003472  Office Supplies
10192  New York City  ...     East  TEC-PH-10004774       Technology
10193  Charlottetown  ...     East  OFF-BI-10004040  Office Supplies

      Sub-Category                                       Product Name  \
0            Paper  Message Book, Wirebound, Four 5 1/2" X 4" Form...
1          Binders         GBC Standard Plastic Binding Systems Combs
2           Labels                                          Avery 508
3          Storage                      SAFCO Boltless Steel Shelving
4              Art  Avery Hi-Liter EverBold Pen Style Fluorescent ...
...            ...                                                ...
10189      Binders               Wilson Jones Legal Size Ring Binders
10190      Binders                                 GBC Binding covers
10191    Fasteners                                Bagged Rubber Bands
10192       Phones                          Gear Head AU3700S Headset
10193      Binders                        Wilson Jones Impact Binders

         Sales Quantity  Discount   Profit  Delivery Days
0       16.448        2       0.2   5.5512              4
1        3.540        2       0.8  -5.4870              4
2       11.784        3       0.2   4.2717              4
3      272.736        3       0.2 -64.7748              4
4       19.536        3       0.2   4.8840              7
...        ...      ...       ...      ...            ...
10189   52.776        3       0.2  19.7910              4
10190   20.720        2       0.2   6.4750              4
10191    3.024        3       0.2  -0.6048              4
10192   90.930        7       0.0   2.7279              4
10193    3.024        3       0.2  -0.6048              4

[10194 rows x 22 columns]>

In [19]:
from numpy.random.mtrand import f
region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

region_sales

Region
West       739813.6085
East       691828.1680
Central    503170.6728
South      391721.9050
Name: Sales, dtype: float64

In [20]:
fig =px.bar(
    region_sales,
    title='Total Sales by Region',
    labels={'value':'Sales'}
)

fig.show()

In [21]:
top_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)
top_products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [22]:
fig =px.bar(
    top_products,
    title='Top 10 Products by Sales',
    labels={'value':'Sales'}
)

fig.show()

In [23]:
category_profit =df.groupby('Category')['Profit'].sum()

category_profit

Category
Furniture           19729.9956
Office Supplies    126023.4434
Technology         146543.3756
Name: Profit, dtype: float64

In [24]:
fig =px.pie(
    values=category_profit.values,
    names=category_profit.index,
    title='Profit Distribution by category'
)

fig.show()

In [25]:
segment_sales = df.groupby('Segment')['Sales'].sum()

segment_sales

Segment
Consumer       1.170660e+06
Corporate      7.158061e+05
Home Office    4.400684e+05
Name: Sales, dtype: float64

In [26]:
fig =px.bar(
    segment_sales,
    title='Sales by Customer Segment'
)

fig.show()

In [27]:
df['Delivery Days'].mean()

np.float64(3.9613498136158523)

In [30]:
ship_mode = df.groupby('Ship Mode')['Delivery Days'].mean()
ship_mode

Ship Mode
First Class       2.182171
Same Day          0.043876
Second Class      3.237999
Standard Class    4.995425
Name: Delivery Days, dtype: float64

In [31]:
fig =px.bar(
    ship_mode,
    title='Total Sales by Region',
)

fig.show()

In [32]:
df['Order Year'] = df['Order Date'].dt.year

In [33]:
yearly_sales = df.groupby('Order Year')['Sales'].sum()
yearly_sales

Order Year
2023    494040.2121
2024    472993.0310
2025    613933.5800
2026    745567.5312
Name: Sales, dtype: float64

In [35]:
fig =px.line(
    yearly_sales,
    title='Yearly Sales Trend',

)

fig.show()